exports.PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';
exports.INVALID_ARGUMENTS = 'INVALID_ARGUMENTS';
exports.ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND';
exports.NOT_LOGIN = 'NOT_LOGIN';
exports.USER_NOT_FOUND = 'USER_NOT_FOUND';
exports.USER_EXISTS = 'USER_EXISTS';
exports.POST_NOT_FOUND = 'POST_NOT_FOUND';
